### ISSUE TITLE
Создание пакета

### ISSUE THREAD

**Issue by maximlit** [0test/evo-newdocs#4]
#evo 3.1.12 
выполнение php artisan package:create main приводит к ошибке
Warning: require(D:\WEB\OpenServer\domains\eee\core\vendor\illuminate\collections\helpers.php): failed to open stream: No such file or directory in D:\WEB\OpenServer\domains\eee\core\vendor\composer\autoload_real.php on line 55

Fatal error: require(): Failed opening required 'D:\WEB\OpenServer\domains\eee\core\vendor\composer/../illuminate/collections/helpers.php' (include_path='.') in D:\WEB\OpenServer\domains\eee\core\vendor\composer\autoload_real.php on line 55

консоль во время выполнения сыплет ошибками
Куда копать не пойму
Спасибо!

![screenshot 749](https://user-images.githubusercontent.com/11734457/196331335-caa0e5c8-a738-40d9-9b62-395ee682f29a.jpg)

**Comment by 0test** [comment]
Версия какая в консоли?
```
php -v
```

**Comment by maximlit** [comment]
7.4

**Comment by 0test** [comment]
На всякий случай -- `composer update` из папки core, а потом уже всё остальное.

**Comment by maximlit** [comment]
Спасибо! Отработало корректно.
